apiVersion: v1
kind: Service
metadata:
  name: department-service-svc
spec:
  selector:
    app: sample-department-service
    tier: department-service
  type: LoadBalancer
  ports:
    ## While running on production cluster, please use 'port: 80'
    - port: 8080
      targetPort: 8080